@echo off
REM Portable Beta Autonomy System - Detects location automatically
REM This script can be moved anywhere with the MidnightCore folder

echo ===============================================================
echo Starting Portable Beta Autonomy System
echo ===============================================================
echo.

REM Get the directory where this script is located and navigate to MidnightCore root
set "SCRIPT_DIR=%~dp0"
set "MIDNIGHT_CORE_ROOT=%SCRIPT_DIR%..\..\.."

echo Script location: %SCRIPT_DIR%
echo MidnightCore root: %MIDNIGHT_CORE_ROOT%
echo.

REM Check if we have the required structure
if not exist "%MIDNIGHT_CORE_ROOT%\Core\Engine\Qwen_Brain_ActiveTesting.py" (
    echo ERROR: Cannot find Qwen_Brain_ActiveTesting.py
    echo Please ensure this script is in the MidnightCore structure
    pause
    exit /b 1
)

if not exist "%MIDNIGHT_CORE_ROOT%\Core\Engine\osc_client.py" (
    echo ERROR: Cannot find osc_client.py
    echo Please ensure this script is in the MidnightCore structure
    pause
    exit /b 1
)

if not exist "%MIDNIGHT_CORE_ROOT%\Core\Common\.venv\Scripts\python.exe" (
    echo ERROR: Cannot find Python virtual environment
    echo Please ensure the .venv is properly set up in Core\Common\.venv
    pause
    exit /b 1
)

echo ✓ All required files found
echo.
echo This will start:
echo 1. Beta Brain - Analysis, reasoning, and command generation
echo 2. OSC Client - Command execution (managed by brain)
echo.
echo Brain automatically manages all subsystems including OSC client
echo Commands are generated by Beta and executed by managed OSC client
echo.
echo Press Ctrl+C to stop the entire system
echo Emergency stop: Run EMERGENCY_STOP.bat in this directory
echo.
echo ===============================================================
echo              SETUP PREPARATION
echo ===============================================================
echo.
echo Before starting Beta, please:
echo 1. Move any panels or windows out of Beta's view
echo 2. Position VRChat window for optimal visibility
echo 3. Ensure VRChat is focused and ready
echo.
echo Press any key when ready to start Beta's vision system...
pause
echo.
echo Starting Beta in 3 seconds...
timeout /t 3 /nobreak >nul
echo.
echo ===============================================================

REM Start Beta Brain (which will manage OSC client automatically)
echo Starting Beta Brain with Managed OSC Client...
echo.
cd /d "%MIDNIGHT_CORE_ROOT%"
"%MIDNIGHT_CORE_ROOT%\Core\Common\.venv\Scripts\python.exe" -m Core.Engine.Qwen_Brain_ActiveTesting

echo.
echo Beta Brain stopped.
echo All managed subsystems have been terminated.
echo If needed, run EMERGENCY_STOP.bat to ensure complete cleanup.
pause